[tool.commitizen]
name = "cz_customize"
version_provider = "pep621"
tag_format = "$version"
version_scheme = "semver"
version_files = [
    "VERSION",
    "pyproject.toml:version"
]
update_changelog_on_bump = true
major_version_zero = true
template = "templates/.changelog_template.j2"

[tool.commitizen.customize]
message_template  = "{{prefix}}({{scope}}): {{subject}}\n\n{{body}}\n\n\n{{footer}}"
schema            = "<prefix>(<scope>): <subject>\n\n<body>\n\n\n<footer>"
schema_pattern    = "^(?P<prefix>(build|bump|ci|chore|docs|feat|fix|perf|refactor|style|test))(?:\\((?P<scope>[a-zA-Z0-9-_]+)\\))?:\\s(?P<subject>.+)(?:\n\n(?P<body>.+))?(?:\n\n\n(?P<footer>.+))?" # noqa: E501
commit_parser     = "^(?P<prefix>(build|bump|ci|chore|docs|feat|fix|perf|refactor|style|test))(?:\\((?P<scope>[a-zA-Z0-9-_]+)\\))?:\\s(?P<subject>.+)(?:\n\n(?P<body>.+))?(?:\n\n\n(?P<footer>.+))?" # noqa: E501
changelog_pattern = "^(?P<prefix>(build|ci|bump|chore|docs|feat|fix|perf|refactor|style|test))(?:\\((?P<scope>[a-zA-Z0-9-_]+)\\))?:\\s(?P<subject>.+)(?:\n\n(?P<body>.+))?(?:\n\n\n(?P<footer>.+))?" # noqa: E501
bump_map = { "BREAKING CHANGE" = "MAJOR", "feat" = "MINOR", "fix" = "PATCH", "refactor" = "PATCH", "perf" = "PATCH" } # noqa: E501
bump_pattern = "^(?P<prefix>(BREAKING CHANGE|feat|fix|refactor|perf))"

[[tool.commitizen.customize.questions]]
type = "list"
name = "prefix"
choices = [
    {value = "build",    key = 'b', name = "build:    Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"}, # noqa: E501
    {value = "ci",       key = 'c', name = "ci:       Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"}, # noqa: E501
    {value = "chore",    key = 'h', name = "chore:    Miscellaneous commits e.g. modifying .gitignore"}, # noqa: E501
    {value = "docs",     key = 'd', name = "docs:     Documentation only changes"},
    {value = "feat",     key = 'f', name = "feat:     A new feature"},
    {value = "fix",      key = 'x', name = "fix:      A bug fix"},
    {value = "perf",     key = 'p', name = "perf:     A code change that improves performance"},
    {value = "refactor", key = 'r', name = "refactor: A code change that neither fixes a bug nor adds a feature"}, # noqa: E501
    {value = "style",    key = 's', name = "style:    Changes that do not affect the meaning of the code"}, # noqa: E501
    {value = "test",     key = 't', name = "test:     Adding or correcting tests"}
]
message = "Select the type of change you are committing"

[[tool.commitizen.customize.questions]]
type    = "input"
name    = "scope"
message = "What is the scope of this change? (class or file name): (press [enter] to skip)\n"

[[tool.commitizen.customize.questions]]
type = "input"
name = "subject"
message = "Write a short and imperative summary of the code changes: (lower case and no period)\n"

[[tool.commitizen.customize.questions]]
type = "input"
name = "body"
message = "Provide additional contextual information about the code changes: (press [enter] to skip)\n" # noqa: E501

[[tool.commitizen.customize.questions]]
type = "confirm"
message = "Is this a BREAKING CHANGE? Correlates with MAJOR in SemVer"
name = "is_breaking_change"
default = false

[[tool.commitizen.customize.questions]]
type = "input"
name = "footer"
message = "Footer. Information about Breaking Changes and reference issues that this commit closes: (press [enter] to skip)\n" # noqa: E501
