# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files #Prevent giant files from being committed.
    -   id: check-case-conflict #Check for files with names that would conflict on a case-insensitive filesystem
    -   id: check-json #Attempts to load all json files to verify syntax.
    -   id: check-merge-conflict #Check for files that contain merge conflict strings.
    -   id: check-toml #Attempts to load all toml files to verify syntax.
    -   id: check-xml #Attempts to load all xml files to verify syntax.
    -   id: check-yaml #Attempts to load all yaml files to verify syntax.
    -   id: end-of-file-fixer #Makes sure files end in a newline and only a newline.
    -   id: mixed-line-ending #Replaces or checks mixed line ending
    -   id: pretty-format-json #Checks that all your JSON files are pretty. "Pretty" here means that keys are sorted and indented.
        args: ['--autofix']
    -   id: requirements-txt-fixer #Sorts entries in requirements.txt and constraints.txt
    -   id: trailing-whitespace #Trims trailing whitespace.
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.31.0
    hooks:
    - id: commitizen
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.0
  hooks:
    # Run the linter.
    - id: ruff
      args: ['--fix']
    # Run the formatter.
    - id: ruff-format
